package main.java.de.car2go.gui;

public enum GUIAction {

    INSERT_GUTACHTEN, UPDATE_GUTACHTEN ,DELETE_GUTACHTEN, INSERT_KUNDEN, INSERT_FAHRZEUGE, INSERT_VERTRAEGE, RAISE_WAGES_20, DELETE_KUNDEN, SELECT_VERMIETER;
}
